FROM python:3.12.6-slim
RUN mkdir workspace
WORKDIR /workspace
COPY . .
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean
RUN pip install poetry
RUN poetry config virtualenvs.create false
ENV PYTHONPATH=/workspace/app:${PYTHONPATH}
RUN poetry install --no-root